Create Log4j informational page
PurpurMC/PurpurDocs pull request #30
Opened 2021-12-14 20:35 UTC by Encode42

This is designed to inform the public about the exploit and how to take action.

Needs an informed and basic explanation on why and how the exploit works.

2021-12-14 21:05 UTC, granny requested changes

2021-12-14 21:05 UTC, granny commented on mkdocs/Log4j.md
> +As stated above, Purpur does not provide a patched jar. Instead, we provide an XML file that disables what causes the exploit. To install, [download this XML file](https://api.purpurmc.org/hotfixes/1
store the xml file in PurpurDocs

2021-12-14 21:05 UTC, granny commented on mkdocs/Log4j.md
> +Current knowledge indicates that all versions of Java can allow remote code execution, according to [Paper’s team](https://discord.com/channels/289587909051416579/289587909051416579/91896426941503085
not everyone has access to paper's discord; replace link with screenshot of the message

2021-12-14 21:05 UTC, granny commented on mkdocs/Log4j.md
> +For more information, read [Mojang’s blog post about the vulnerability](https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition). It contains fixes for other pl
not everyone has access to paper's discord; replace link with screenshot of the message

2021-12-14 21:05 UTC, granny commented on mkdocs/Log4j.md
> +The process is the same as the above, but with a different XML file. [Download this XML file](https://api.purpurmc.org/hotfixes/1.16.5/purpur_log4j2_1141-1165.xml) to your server’s root directory, an
store the xml file in PurpurDocs

2021-12-14 21:05 UTC, granny commented on mkdocs/Log4j.md
> +All 1.18.1 builds and newer are patched, as this exploit was one of the reasons it was released. If you’re running 1.18, builds [#1433](https://api.purpurmc.org/v2/purpur/1.18/1433/download) and newe
add a link to the latest build somewhere

2021-12-14 21:55 UTC, Encode42 commented
note: mkdocs does not support footnotes :(

2021-12-15 17:03 UTC, Encode42 commented
Need to look into [the new CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046)

2021-12-19 04:57 UTC, granny approved these changes

2021-12-19 04:57 UTC, merged