Explain the per world settings
PurpurMC/PurpurDocs pull request #42
Opened 2022-03-12 22:10 UTC by jacksyyy

there is issue with MANY people not knowing about how to use the per world settings. the PurpurDocs do not explain it. they just say default. so I add more! this is simple to follow with example

2022-03-12 22:24 UTC, BillyGalbreath requested changes

2022-03-12 22:24 UTC, BillyGalbreath commented on mkdocs/Configuration.md
> +```
spawn chunks or starvation damage? ;)

2022-03-12 22:25 UTC, BillyGalbreath commented
We (the bukkit communities) have generally been passing around this pdf: https://www.spigotmc.org/attachments/per-world-guide-pdf.444348/

2022-03-12 22:28 UTC, jacksyyy commented
I can not view pdf because it requires the spigotmc account that I do not have. I will make one to view, but I think having included in docs is good idea anyways. PDF is format of the 2000s. it is 2022. I think it is possible many server owner are not used to PDF.

2022-03-16 00:37 UTC, granny commented
I noticed that this explanation is nearly identical to Paper's; https://docs.papermc.io/paper/per-world-configuration

Decided to just link readers to their page. This means I won't have to worry about inconsistencies between our pages or have to keep something updated when there's hardly any difference between the two pages.

Appreciate the PR nonetheless!

2022-03-16 00:37 UTC, closed without merging